In [0]:
#Bhargav Muktevi ,Chaitanya Upadrasta, Sharanya Hunasamranahalli Thotadarya
import numpy as np
import os
import tensorflow as tf
from time import time
from google.colab import drive

In [2]:
drive.mount('/content/drive/')
%cd 'drive/My Drive/Colab Notebooks'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/
/content/drive/My Drive/Colab Notebooks


In [3]:
!python prepare_data.py shakespeare.txt skp
#!python prepare_data.py shakespeare.txt skp -l 400
#To change the sequence length by default it is 200

2020-05-26 08:15:25.360401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Split input into 22981 sequences...
Serialized 100 sequences...
Serialized 200 sequences...
Serialized 300 sequences...
Serialized 400 sequences...
Serialized 500 sequences...
Serialized 600 sequences...
Serialized 700 sequences...
Serialized 800 sequences...
Serialized 900 sequences...
Serialized 1000 sequences...
Serialized 1100 sequences...
Serialized 1200 sequences...
Serialized 1300 sequences...
Serialized 1400 sequences...
Serialized 1500 sequences...
Serialized 1600 sequences...
Serialized 1700 sequences...
Serialized 1800 sequences...
Serialized 1900 sequences...
Serialized 2000 sequences...
Serialized 2100 sequences...
Serialized 2200 sequences...
Serialized 2300 sequences...
Serialized 2400 sequences...
Serialized 2500 sequences...
Serialized 2600 sequences...
Serialized 2700 sequences...
Serialized 2800 sequences...
Serialized 2900

In [4]:
from prepare_data import parse_seq
import pickle

# this is just a datasets of "bytes" (not understandable)
data = tf.data.TFRecordDataset("skp.tfrecords")

# this maps a parser function that properly interprets the bytes over the dataset
# (with fixed sequence length 200)
# if you change the sequence length in preprocessing you also need to change it here
data = data.map(lambda x: parse_seq(x, 200))

# a map from characters to indices
vocab = pickle.load(open("skp_vocab", mode="rb"))
vocab_size = len(vocab)
# inverse mapping: indices to characters
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}

print(vocab)
print(vocab_size)

{'$': 1, 'P': 2, 'L': 3, 'v': 4, 'X': 5, 'e': 6, 'O': 7, 'j': 8, 'z': 9, 'g': 10, 's': 11, 'D': 12, '?': 13, 'Q': 14, 'l': 15, ']': 16, 'R': 17, 'U': 18, 'A': 19, '-': 20, 'i': 21, ',': 22, 'o': 23, 'B': 24, ':': 25, 'G': 26, 'm': 27, 'N': 28, '.': 29, 'K': 30, 'T': 31, 'V': 32, 'f': 33, 'p': 34, 'r': 35, ';': 36, 'h': 37, 'Z': 38, 'F': 39, 'd': 40, 'E': 41, '3': 42, 'k': 43, 'b': 44, 'Y': 45, "'": 46, 'n': 47, 'I': 48, '!': 49, 'x': 50, ' ': 51, 'W': 52, 'a': 53, '&': 54, 'S': 55, 'u': 56, '[': 57, '\n': 58, 'q': 59, 'y': 60, 'c': 61, 'M': 62, 'J': 63, 'w': 64, 'H': 65, 'C': 66, 't': 67, '<S>': 0}
68


# Trail : Onhot encoding and batch

In [5]:
#One hot encoding
for x in data:
  onehotvector = tf.one_hot(x,depth=vocab_size)
  print(onehotvector)
  break


#sequences are stored in data perfroming a batch size of 128 to for training
training_data = data.batch(128)
count = 0
for y in training_data:
  #print(y.shape)
  count += 1
#print(count)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(200, 68), dtype=float32)


In [0]:
#Weight Initialization

hidden_size = 512
W_xh = tf.Variable(tf.random.uniform([vocab_size,hidden_size]))
W_hh = tf.Variable(tf.random.uniform([hidden_size,hidden_size]))
W_ho = tf.Variable(tf.random.uniform([hidden_size,vocab_size]))
b_h = tf.Variable(tf.random.uniform([1,hidden_size]))
b_o = tf.Variable(tf.random.uniform([1,vocab_size]))
#firststate = tf.Variable(tf.zeros([1,hidden_size]))



In [0]:
training_steps = 100 

In [8]:
for step,batch in enumerate(training_data):
    print(len(batch))
     #batch = tf.one_hot(batch,depth =vocab_size)
    #with tf.GradientTape() as tape:
           #xent = 0.0

    for ind1,sequence in enumerate(batch):
               #with tf.GradientTape() as tape:

                     Onehotvector = tf.one_hot(sequence,depth =vocab_size)
                     #Truevalue = tf.cast(tf.roll(sequence,-1,axis=0),tf.int64)
                     firststate = tf.Variable(tf.zeros([1,hidden_size]))
                     #predicted = []
                     xent = 0.0
                    
             
                     for ind, char in enumerate(Onehotvector): 
                             with tf.GradientTape() as tape:
                              
                                 X=tf.reshape(char,shape=[-1,vocab_size])
                                 if ind == 199:
                                     target = sequence[0]
                                 else:
                                     target = sequence[ind+1]

                                 Inputchar = tf.matmul(X,W_xh)
                                 Previous_state = tf.matmul(firststate, W_hh)
                                 newState = tf.nn.tanh(Inputchar + Previous_state + b_h)   
                                 logits1 = tf.nn.tanh(tf.add(tf.matmul(newState,W_ho),b_o))
                                  #predicted.append(tf.nn.softmax(logits=logits1))
                                 Previous_state = newState
                                  #Truevalue = tf.reshape(Truevalue,[200,1])
                                 xent +=tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits1, labels=[target])
                     grads = tape.gradient(xent, [W_ho, b_o, W_hh, b_h, W_xh])
                     optimizer = tf.optimizers.Adam(learning_rate = 0.001)
                     optimizer.apply_gradients(zip(grads, [W_ho, b_o, W_hh, b_h, W_xh]))
                                  #print(xent)
                             

                     #xent = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=predicted, labels=Truevalue))
                     #grads = tape.gradient(xent, [W_ho, b_o, W_hh, b_h, W_xh])
                     #optimizer = tf.optimizers.Adam(learning_rate = 1e-1)
                     #Afterclipping = [(tf.clip_by_value(grad, -0.5, 0.5)) for grad in grads]
                     #optimizer.apply_gradients(zip(Afterclipping, [W_ho, b_o, W_hh, b_h, W_xh]))
                     #print(xent)
             
                 
                    
           
        
      
   

128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
128
69


In [12]:
#Text Generation

# Creating a mapping from unique characters to indices
char2idx = {u:i for i, u in enumerate(vocab)}
#print(char2idx)
idx2char = np.array(vocab)

idx2char = idx2char.tolist()
num_generate = 500
start_string = '<S>'
h_0 = tf.Variable(tf.zeros([1,hidden_size]))
prev_h = h_0
vocab_siz = 68
#print(oldstep)

# input_eval = [char2idx[s] for s in start_string] # For any other symbol


input_eval = [char2idx[start_string]] #For start symbol
input_eval = tf.expand_dims(input_eval, 0)

input_eval = tf.one_hot(input_eval, vocab_size)

text_generated = []

for i in range(num_generate):
  inp = tf.matmul(input_eval,W_xh)
  prev_h = tf.matmul(prev_h, W_hh)
  hidden_layer1 = tf.nn.tanh(inp + prev_h + b_h)
  prev_h = hidden_layer1

  predictions = tf.nn.tanh(tf.matmul(hidden_layer1,W_ho) +b_o)
  #print(predictions)
  predictions = tf.squeeze(predictions, 0)
  #print(predictions.shape)

  # predictions = predictions / temperature
  # print(predictions)
  predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
  #print(predicted_id)
  input_eval = tf.expand_dims([predicted_id], 0)
  #print(input_eval)
  input_ev = tf.expand_dims([predicted_id], 0)
  #print(input_ev)
  input_eval = tf.one_hot(input_ev, vocab_size)
  #print(input_eval)

  for key, value in idx2char.items(): 
    if input_ev == value: 
      predicted_id = key

  text_generated.append(predicted_id)
start_string + ''.join(text_generated)



"<S>qzP IGfUG:le:TFW:UppZWKfyS$xIcRAsi;\nyw uu'&UB$tm\n]?!scAugdfrj's] bbOd.kmYF3y T'Ro$defioQr[cSS?Vuo,T'HFxyhgyKD?TdkXjdc:[Uy'T,WDmobLODrzIBPp3rlKF<S>!nRTgabFVsJyqG$<S>B]px&tdVmo,DRWLH'hCsVPdEi<S>.mB<S>r--n\n;P<S>m<S>RsqK<S>fp\nXIzXJk&KG!l!AIhLQgBYHySjLnQ?t<S>$;tlCb\njQJ'K\nL$!DMGuSlv]V?LypYrShoU\nZlE&H;oT' VTf'QapjVryxtdcpsM,LhjjNQds,koRydq!C!MqLTkc.weFbRuUjlmbD ;.fcZiprZjP\npQq'difKBvmLie3BaeWhM\naKLlYfRRJPI:SAjBB!BhjjNWK?&Ai.YLm:ZYrb vzIYQ,eKszCxvx:olsQcGvY,Qxoz3B\nLF?Ghn'eSrDOoEyra<S>m]\nOOakuv\n<S>OAgfEkHfLNfYRxq-F?NlCnRl!-"