In [0]:
#Bhargav Muktevi ,Chaitanya Upadrasta, Sharanya Hunasamranahalli Thotadarya

In [0]:
import tensorflow as tf

# **1.Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.**

In [0]:
@tf.function
def topk(input, k):
  if input.shape[1] < k:
    return "Not valid K value"
 
   
  return tf.math.top_k(input, k)[0]
  

In [0]:
RandomVariable = tf.Variable(tf.random.uniform([10,20],minval=1,maxval=20,dtype=tf.int32))
print(RandomVariable.shape)
print(RandomVariable)
print(RandomVariable.shape[1])

output = topk(RandomVariable,4)


print(output)

(10, 20)
<tf.Variable 'Variable:0' shape=(10, 20) dtype=int32, numpy=
array([[ 4, 19, 11, 16, 19, 10,  5, 17,  5, 19, 10, 19,  4,  7,  4, 15,
         1, 14,  3,  5],
       [ 5,  1, 11, 19, 18, 11,  4,  8, 12,  4,  9,  1, 19,  5, 16, 16,
        14,  2, 16,  5],
       [15, 18,  1,  2,  2, 17, 12, 19, 10,  4,  1, 11, 15, 11, 13,  1,
        11, 19, 17, 16],
       [19, 15, 14,  6,  9, 14,  9,  4,  5,  8, 16,  7, 14,  1, 19,  9,
        12, 14, 17, 18],
       [ 5,  9, 11,  4, 12,  7,  4,  9,  2, 17, 19, 17,  7, 15, 11,  7,
        17, 17, 14,  9],
       [18,  7,  9,  2,  1,  6,  4, 15, 10, 10,  9,  9,  3,  7, 18, 15,
        16, 10, 15, 12],
       [ 8,  3,  4, 14, 19,  4, 11, 17, 18, 15, 18, 16, 10,  3,  6, 11,
        16,  4, 13, 13],
       [18, 19,  8,  7,  3,  6,  6,  9,  4,  8,  1, 15, 10,  3,  8,  1,
        18, 11,  9, 17],
       [ 3,  5,  3,  5, 10,  8, 17, 13, 16,  6, 11,  7, 14, 12, 16,  9,
         8,  2,  1, 15],
       [ 1, 15,  6,  9,  8, 16, 12,  1, 12, 10, 18,  7, 1

# **2.Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.**

In [0]:
@tf.function
def argmax_output(input):
  argmax_row = tf.math.argmax(input,axis=1)
  print("the shape is",argmax_row.shape)
  argmax_onehot = tf.one_hot(argmax_row,input.shape[1])
  print(input.shape[0])
  print(input.shape[1])

  return argmax_onehot

In [0]:
RandomVariable = tf.Variable(tf.random.uniform([10,20],minval=1,maxval=30,dtype=tf.int32))
print(RandomVariable.shape)
print(RandomVariable)
output = argmax_output(RandomVariable)
print(output)

(10, 20)
<tf.Variable 'Variable:0' shape=(10, 20) dtype=int32, numpy=
array([[19, 26, 21,  6, 19,  5,  1, 21, 27,  5, 16,  1, 25, 14, 20, 20,
        17, 13, 27, 24],
       [18, 19, 22,  7, 13, 25, 18, 25,  7, 20, 22, 14,  9, 14, 19, 27,
        24, 27, 19, 19],
       [12, 28,  1, 23,  9, 12, 25, 28, 20, 14, 11,  2, 10,  8,  6, 20,
         4,  2,  5, 24],
       [15, 13, 10, 10,  8, 28, 16, 13, 27, 10,  6, 16, 12, 12,  7, 16,
        13, 11, 29, 24],
       [28,  3, 19, 15, 15, 26,  1, 25, 11, 12,  9,  4,  3, 24, 22, 14,
        16, 27, 24, 21],
       [26,  3, 16,  4, 26,  3,  5,  2,  6,  8, 22, 27,  8, 27, 25, 16,
        14, 29,  4, 16],
       [28,  2, 15, 22, 25, 23, 23, 23,  6, 24, 27, 25, 11, 26, 16,  2,
        18, 19, 25,  5],
       [16, 20, 23,  7, 12,  1, 10, 16, 15,  2, 22, 27,  9, 11, 12,  7,
         9, 28,  8,  1],
       [ 7, 10, 17, 19, 26, 11, 24, 16, 14,  5, 17, 13, 18, 26,  6, 27,
        19,  7, 20,  7],
       [28, 17, 29,  4, 27, 27, 29, 28,  4, 24,  9, 25,  

# **As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.**

In [0]:
@tf.function
def topk_1D_tensor(input, k):
  values, indices = tf.math.top_k(input,k)
  print(indices.shape)
  print(values.shape)
  indices = tf.reshape(indices, (k,1))
  return tf.scatter_nd(indices, values, input.shape)


In [0]:
RandomVariable = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))
print(RandomVariable)
print("*******************")
output = topk_1D_tensor(RandomVariable,4)
print(output)

<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([ 7, 22, 14, 19,  6, 25,  4, 18,  6, 19,  1, 15, 26, 19, 25, 15, 22,
        2,  4, 11], dtype=int32)>
*******************
(4,)
(4,)
tf.Tensor([ 0 22  0  0  0 25  0  0  0  0  0  0 26  0 25  0  0  0  0  0], shape=(20,), dtype=int32)


In [0]:
@tf.function 
def topk_2D_tensor(input, k):
  def topk_1D_tensor(input):
    values, indices = tf.math.top_k(input,k)
    indices = tf.reshape(indices, (k,1))
    return tf.scatter_nd(indices, values, input.shape)
  
  output = tf.map_fn(topk_1D_tensor,input)
  return output

In [0]:
RandomVariable = tf.Variable(tf.random.uniform([10,20],minval=1,maxval=30,dtype=tf.int32))
print(RandomVariable)
print("*******************")
output = topk_2D_tensor(RandomVariable,4)
print(output)

<tf.Variable 'Variable:0' shape=(10, 20) dtype=int32, numpy=
array([[ 8, 16, 10, 16, 24, 17, 12, 26, 22, 14, 19, 15,  5,  5, 17, 15,
         3, 21, 20, 20],
       [25, 18, 24, 26, 27, 20, 16, 23,  9, 17, 14,  3,  7,  4, 28, 25,
        16, 12,  3, 11],
       [28, 17, 15,  4, 22,  6,  3, 22,  5, 25,  9, 13, 16, 24, 16, 18,
        28, 12,  8, 24],
       [27, 18, 22, 29, 10, 14,  2, 13,  3,  3,  8, 21,  9, 24, 13, 22,
         3,  2,  3,  8],
       [15, 19, 22, 21, 23, 14, 19, 18,  2,  6,  6, 13, 23, 22,  1, 12,
        17, 15, 18, 27],
       [16, 17,  6, 12, 20, 25, 13,  6,  7, 11,  1, 11, 28, 26,  3,  9,
        28, 29, 20, 25],
       [18, 16,  1, 29, 27, 14, 12,  6, 13,  9, 24, 27,  5,  3, 10,  6,
         7, 14,  5, 18],
       [19,  9,  7, 20, 25,  9, 18, 26, 21, 17, 20, 19,  9, 16, 22,  1,
         1, 24, 19, 20],
       [ 7, 11, 19, 28,  2, 18,  1, 19, 24, 22, 16, 22, 10, 21, 21,  4,
         4, 19, 11,  4],
       [25, 13, 24,  1, 15, 27, 20, 12,  2, 19,  7, 20, 15, 28,  8

# 4.Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage 

In [0]:

@tf.function
def exponential_moving_average(input, a):
  ouput = [] 
  for i in range(input.shape[0]):
    #print("this is i",i)
    if i == 0:
      ouput.append(input[i])
    else:
      ouput.append(a * ouput[i-1] + (1-a)*input[i]) #2*26-8
      #print("this is output",output)
  return tf.stack(ouput)

In [0]:
RandomVariable = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))
print(RandomVariable)
print("*******************")
output = exponential_moving_average(RandomVariable,2)
print(output)

<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([26,  8,  4, 13,  9, 13,  7, 25, 13, 16, 25, 22, 18, 12, 11, 10,  8,
        4, 11, 23], dtype=int32)>
*******************
tf.Tensor(
[     26      44      84     155     301     589    1171    2317    4621
    9226   18427   36832   73646  147280  294549  589088 1178168 2356332
 4712653 9425283], shape=(20,), dtype=int32)


# **5.Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it).**

In [0]:
#@tf.function
def exponential_moving_average_last_element(input, a, i):
  if i == 0:
    return input[0]
  else:
    return a * exponential_moving_average_last_element(input,a,i-1) + (1-a) * input[i]

In [0]:
RandomVariable = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))
print(RandomVariable)
print("*******************")
output = exponential_moving_average_last_element(RandomVariable,2,3)
print(output)

<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([ 3, 19, 25, 11, 28,  2, 14,  1, 15,  1,  9,  9, 13,  4,  5, 24, 28,
       18, 20, 15], dtype=int32)>
*******************
tf.Tensor(-113, shape=(), dtype=int32)


# **6.Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.**

In [0]:
@tf.function
def even_odd(a, b, c):
  stack = tf.stack([a,b,c], 0)
  print(stack.shape)
  return tf.map_fn(lambda t: t[1] if t[0]%2 == 0 else t[2], tf.transpose(stack))

In [0]:
x = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))
y = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))
z = tf.Variable(tf.random.uniform([20],minval=1,maxval=30,dtype=tf.int32))

print(x)
print(y)
print(z)
output = even_odd(x, y, z)
print(output)

<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([29,  7,  1, 10, 10,  7,  2,  8,  5,  5, 26,  7,  8, 24, 11, 10, 29,
        8,  8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([24, 17, 29, 13, 12, 14,  8, 14, 12, 13, 19,  8,  5, 26, 24,  8,  5,
       19, 21, 29], dtype=int32)>
<tf.Variable 'Variable:0' shape=(20,) dtype=int32, numpy=
array([26,  8, 23,  1, 15,  1,  5, 21,  6,  2, 21, 20, 29,  9,  3, 27, 10,
        5, 14, 20], dtype=int32)>
(3, 20)
tf.Tensor([26  8 23 13 12  1  8 14  6  2 19 20  5 26  3  8 10 19 21 29], shape=(20,), dtype=int32)


# **7.Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.**

In [0]:

@tf.function
def last_dimension_size(input):
  shape = input.shape
  print(shape)
  last_dimension = shape[len(shape)-1]
  print(last_dimension)

  if last_dimension > 100:
    return 100
  elif last_dimension >= 44:
    return 12
  else:
    return 0



In [0]:
RandomVariable = tf.Variable(tf.random.uniform((2,3,400)))
#print(RandomVariable)

output = last_dimension_size(RandomVariable)

print("*************************")
print(output)

(2, 3, 400)
400
*************************
tf.Tensor(100, shape=(), dtype=int32)


# 8.**As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?**

In [0]:


counter1 = tf.constant(0)
counter2 = tf.constant(0)
counter3 = tf.constant(0)

def last_dimension(input):
  shape = input.shape
  last_dim = shape[len(shape)-1]

  global counter1
  global counter2
  global counter3

  if last_dim > 100:
    counter1 += 1
    return 100
  elif last_dim >= 44:
    counter2 += 1
    return 12
  else:
    counter3 += 1
    return 0

@tf.function
def last_dimension_size_counter(input):
  return tf.py_function(last_dimension, [input], Tout=[tf.int32])

In [0]:
RandomVariable = tf.Variable(tf.random.uniform((2,3,340)))

last_dimension_size_counter(RandomVariable)

print(counter1)
print(counter2)
print(counter3)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


# 9.**Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.**

In [0]:
@tf.function
def function1(x, y):
  z = tf.broadcast_to(-y,[x.shape[0], x.shape[0]])
  z += tf.transpose(tf.reshape(x,(1,5)))

  return z

In [0]:
x = tf.Variable(tf.random.uniform([5],minval=1,maxval=30,dtype=tf.int32))
y = tf.Variable(tf.random.uniform([5],minval=1,maxval=30,dtype=tf.int32))

print(x)
print(y)
output = function1(x,y)
print(output)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([22, 23, 15, 25, 25], dtype=int32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([28, 11,  8, 24,  5], dtype=int32)>
tf.Tensor(
[[ -6  11  14  -2  17]
 [ -5  12  15  -1  18]
 [-13   4   7  -9  10]
 [ -3  14  17   1  20]
 [ -3  14  17   1  20]], shape=(5, 5), dtype=int32)


10.Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i. **bold text**

In [0]:
@tf.function
def function10(x, y):
  attention = tf.nn.softmax(tf.matmul(x,tf.expand_dims(y,2))[:,:,0],1)

  return attention

In [22]:
import numpy as np
enc_states = tf.Variable(np.random.normal(size=(16,10,32)),shape=[16,10,32],trainable=False,dtype="float32")
dec_states = tf.Variable(np.random.normal(size=(16,32)),shape=[16,32],trainable=False,dtype="float32")

attention = function10(enc_states,dec_states)
print(attention)

tf.Tensor(
[[3.16072116e-03 3.42590868e-01 5.10502141e-05 6.53995454e-01
  1.11437203e-07 3.84636223e-06 9.18134674e-07 3.97726617e-05
  2.01440891e-08 1.57235540e-04]
 [4.05544015e-05 1.29294014e-04 3.90998102e-05 7.38999724e-01
  5.57149947e-03 2.75327625e-06 1.64603710e-01 4.84820717e-04
  7.03430146e-07 9.01279002e-02]
 [4.57409897e-08 2.76453998e-02 1.72856318e-07 4.41386491e-01
  5.20242572e-01 9.46065970e-03 4.00945573e-04 8.63353314e-04
  2.89841440e-09 3.22426672e-07]
 [5.67554780e-05 9.24242300e-08 2.13625623e-04 9.52564418e-01
  3.41258310e-09 9.63712864e-07 6.61480541e-08 1.16632168e-06
  4.70815077e-02 8.13880688e-05]
 [6.49633725e-09 1.00109384e-04 1.35049447e-02 7.97968507e-02
  1.21065845e-04 2.31069134e-04 4.50566202e-01 1.83816358e-01
  5.28561475e-04 2.71334916e-01]
 [1.59110185e-02 2.03213608e-03 2.21519568e-03 1.49604661e-04
  8.93827975e-01 2.39404337e-03 1.02976488e-03 3.48525901e-08
  1.20631034e-08 8.24402124e-02]
 [2.62711523e-03 7.81526029e-01 6.63250976e-04 